### PR TITLE
[FIX] fixing the stub error on `COMPUTE_SIMILARITY_WF` workflow

### LINKED ISSUE #2: Fix the `combine_orthoani_results` module
Hi @Mxrcon,

The following module is raising an error while running the pipeline at the moment for some reason, if possible could you please test this module in isolation using `stubs`?

https://github.com/bioinformatics-lab/camila_sao_paulo_nf/blob/main/modules/utils/combine_orthoani_results_tsv/combine_orthoani_results_tsv.nf

### PR DESCRIPTION
**Pull request by Mxrcon**
Hey, as requested i took some time to check the stub issue mentioned on #2 and it seems to be a small issue on the stub trying to use a variable that doesn't exists. 
I made a small change that made the stub to work, at least the module running on isolation with stubs is working.
This Pull Request Closes #2 

I'm at your disposal to make any necessary changes or discuss the content of this PR, feel free to discuss them with me or criticize if necessary.

Kindly, Davi

### CODE REVIEW

**Comment by abhi18av** [comment]
Thanks for the effort on this @Mxrcon!

Yes, that was expected, however did you check the overall pipeline , mainly this workflow https://github.com/emilyncosta/labmicobact_unifesp_ntm_romagnoli_nf/blob/d29cac6da413163902c04411c817ebecf1873c4f/main.nf#L79  ?

**Comment by Mxrcon** [comment]
Hey @abhi18av I've took some time to check the modifications and test this workflow. I actually had some troubles trying to setup the fasta files for testing, but I got it and tested as requested and those changes should be enough. But i strongly suggest the creation of a param for `orthoani_ch` so we chan change it on stub profile.

**Comment by abhi18av** [comment]
>  But i strongly suggest the creation of a param for orthoani_ch so we chan change it on stub profile.

Could you please elaborate with a code snippet? Perhaps another branch (PR) could be used to discuss this suggestion?

**Comment by Mxrcon** [comment]
I'll raise a PR, i think that is the better option

**Comment by abhi18av** [comment]
Oki doki, I'm merging this PR in the meantime. Thanks for the contrib Davi!

**Comment by Mxrcon** [comment]
:smile:

**Pull request merged**
